### ISSUE TITLE
Doesn't work for Edge

### ISSUE THREAD

**Issue by Haroenv** [bullgit/fuckIE#7]
At least, not in my experience.

An uglier solution would be to use uA checking too, but that isn't pretty.

**Comment by 0x04** [comment]
A possible solution for this is proofing the existence of `window.msWriteProfilerMark`. This function is owned by Internet Explorer >= 8 and Edge. For older Versions we could use `!!window.ActiveXObject`.

**Comment by 0x04** [comment]
Fixed.
